// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: forge.proto

package forgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- RegisterWorker ---
type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	DemoControl   bool                   `protobuf:"varint,2,opt,name=demo_control,json=demoControl,proto3" json:"demo_control,omitempty"` // Explicit opt-in to dashboard failure injection.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_forge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetDemoControl() bool {
	if x != nil {
		return x.DemoControl
	}
	return false
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_forge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// --- GetTask ---
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_forge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasTask       bool                   `protobuf:"varint,1,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_forge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *GetTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// --- ReportResult ---
type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_forge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{4}
}

func (x *ReportResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportResultRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ReportResultRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_forge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{5}
}

func (x *ReportResultResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// --- Heartbeat ---
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_forge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	StopWorker    bool                   `protobuf:"varint,2,opt,name=stop_worker,json=stopWorker,proto3" json:"stop_worker,omitempty"` // Stop without reporting a result; normal leases recover work.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_forge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_forge_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetStopWorker() bool {
	if x != nil {
		return x.StopWorker
	}
	return false
}

var File_forge_proto protoreflect.FileDescriptor

const file_forge_proto_rawDesc = "" +
	"\n" +
	"\vforge.proto\x12\aforgepb\"W\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fdemo_control\x18\x02 \x01(\bR\vdemoControl\"(\n" +
	"\x16RegisterWorkerResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"-\n" +
	"\x0eGetTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"_\n" +
	"\x0fGetTaskResponse\x12\x19\n" +
	"\bhas_task\x18\x01 \x01(\bR\ahasTask\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"\x80\x01\n" +
	"\x13ReportResultRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"&\n" +
	"\x14ReportResultResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"D\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vstop_worker\x18\x02 \x01(\bR\n" +
	"stopWorker2\xb0\x02\n" +
	"\fForgeService\x12Q\n" +
	"\x0eRegisterWorker\x12\x1e.forgepb.RegisterWorkerRequest\x1a\x1f.forgepb.RegisterWorkerResponse\x12<\n" +
	"\aGetTask\x12\x17.forgepb.GetTaskRequest\x1a\x18.forgepb.GetTaskResponse\x12K\n" +
	"\fReportResult\x12\x1c.forgepb.ReportResultRequest\x1a\x1d.forgepb.ReportResultResponse\x12B\n" +
	"\tHeartbeat\x12\x19.forgepb.HeartbeatRequest\x1a\x1a.forgepb.HeartbeatResponseB.Z,github.com/ronavpoonekar/forge/proto/forgepbb\x06proto3"

var (
	file_forge_proto_rawDescOnce sync.Once
	file_forge_proto_rawDescData []byte
)

func file_forge_proto_rawDescGZIP() []byte {
	file_forge_proto_rawDescOnce.Do(func() {
		file_forge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forge_proto_rawDesc), len(file_forge_proto_rawDesc)))
	})
	return file_forge_proto_rawDescData
}

var file_forge_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_forge_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),  // 0: forgepb.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 1: forgepb.RegisterWorkerResponse
	(*GetTaskRequest)(nil),         // 2: forgepb.GetTaskRequest
	(*GetTaskResponse)(nil),        // 3: forgepb.GetTaskResponse
	(*ReportResultRequest)(nil),    // 4: forgepb.ReportResultRequest
	(*ReportResultResponse)(nil),   // 5: forgepb.ReportResultResponse
	(*HeartbeatRequest)(nil),       // 6: forgepb.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 7: forgepb.HeartbeatResponse
}
var file_forge_proto_depIdxs = []int32{
	0, // 0: forgepb.ForgeService.RegisterWorker:input_type -> forgepb.RegisterWorkerRequest
	2, // 1: forgepb.ForgeService.GetTask:input_type -> forgepb.GetTaskRequest
	4, // 2: forgepb.ForgeService.ReportResult:input_type -> forgepb.ReportResultRequest
	6, // 3: forgepb.ForgeService.Heartbeat:input_type -> forgepb.HeartbeatRequest
	1, // 4: forgepb.ForgeService.RegisterWorker:output_type -> forgepb.RegisterWorkerResponse
	3, // 5: forgepb.ForgeService.GetTask:output_type -> forgepb.GetTaskResponse
	5, // 6: forgepb.ForgeService.ReportResult:output_type -> forgepb.ReportResultResponse
	7, // 7: forgepb.ForgeService.Heartbeat:output_type -> forgepb.HeartbeatResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forge_proto_init() }
func file_forge_proto_init() {
	if File_forge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forge_proto_rawDesc), len(file_forge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forge_proto_goTypes,
		DependencyIndexes: file_forge_proto_depIdxs,
		MessageInfos:      file_forge_proto_msgTypes,
	}.Build()
	File_forge_proto = out.File
	file_forge_proto_goTypes = nil
	file_forge_proto_depIdxs = nil
}
