package scheduler

import (
	"context"
	"log"

	"github.com/ronavpoonekar/forge/proto/forgepb"
)

// GRPCServer implements the ForgeServiceServer interface generated by protoc.
// It bridges gRPC calls from workers to the Scheduler's methods.
type GRPCServer struct {
	forgepb.UnimplementedForgeServiceServer
	scheduler *Scheduler
}

func NewGRPCServer(sched *Scheduler) *GRPCServer {
	return &GRPCServer{
		scheduler: sched,
	}
}

// RegisterWorker handles the RegisterWorker RPC — called once when a worker starts.
//
// TODO (Step 5): Implement this method
//
// Steps:
//  1. Call s.scheduler.RegisterWorker(req.WorkerId)
//  2. Log that the worker registered
//  3. Return ok = true
func (s *GRPCServer) RegisterWorker(ctx context.Context, req *forgepb.RegisterWorkerRequest) (*forgepb.RegisterWorkerResponse, error) {
	log.Printf("Worker %s registering", req.WorkerId)

	s.scheduler.RegisterWorker(req.WorkerId)
	
	return &forgepb.RegisterWorkerResponse{
		Ok: true,
	}, nil
}

// GetTask handles the GetTask RPC — called by workers requesting work.
//
// Stage 3 change: pass req.WorkerId to NextTask so the scheduler knows
// which worker is taking the task.
func (s *GRPCServer) GetTask(ctx context.Context, req *forgepb.GetTaskRequest) (*forgepb.GetTaskResponse, error) {
	// Note: NextTask now takes workerID as a parameter (Stage 3 change)
	task := s.scheduler.NextTask(req.WorkerId)

	if task == nil {
		return &forgepb.GetTaskResponse{
			HasTask: false,
		}, nil
	}

	log.Printf("Assigned task %s to worker %s: %s", task.ID, req.WorkerId, task.Command)

	return &forgepb.GetTaskResponse{
		HasTask: true,
		TaskId:  task.ID,
		Command: task.Command,
	}, nil
}

// ReportResult handles the ReportResult RPC — called by workers when a task finishes.
func (s *GRPCServer) ReportResult(ctx context.Context, req *forgepb.ReportResultRequest) (*forgepb.ReportResultResponse, error) {
	log.Printf("Worker %s completed task %s (exit code: %d)", req.WorkerId, req.TaskId, req.ExitCode)

	s.scheduler.CompleteTask(req.TaskId, req.Output, int(req.ExitCode))

	return &forgepb.ReportResultResponse{
		Ok: true,
	}, nil
}
