package scheduler

import (
	"context"
	"log"

	"github.com/ronavpoonekar/forge/proto/forgepb"
)

// GRPCServer implements the ForgeServiceServer interface generated by protoc.
//
// It acts as a BRIDGE between gRPC and your existing Scheduler.
// When a worker calls GetTask over gRPC, this handler translates that into
// a call to Scheduler.NextTask(), and translates the result back into a
// gRPC response.
//
// Think of it as an adapter:
//
//	gRPC request → GRPCServer → Scheduler → GRPCServer → gRPC response
//
// This is why your Stage 1 Scheduler code doesn't change — it still has
// Submit(), NextTask(), CompleteTask(), etc. The GRPCServer just wraps them.
type GRPCServer struct {
	forgepb.UnimplementedForgeServiceServer // required by gRPC — provides default method stubs
	scheduler                               *Scheduler
}

// NewGRPCServer creates a new GRPCServer wrapping the given Scheduler.
func NewGRPCServer(sched *Scheduler) *GRPCServer {
	return &GRPCServer{
		scheduler: sched,
	}
}

// GetTask handles the GetTask RPC — called by workers requesting work.
//
// TODO (Step 3): Implement this method
//
// Steps:
//  1. Call s.scheduler.NextTask()
//  2. If nil (no work), return a response with HasTask = false
//  3. If a task was returned, return a response with HasTask = true,
//     TaskId = task.ID, Command = task.Command
//
// The 'context.Context' parameter is standard for gRPC — it carries
// deadlines, cancellation signals, and metadata. For now you can ignore it,
// but it'll become important in Stage 5 (heartbeats/leases).
//
// Remember: this is called from a gRPC goroutine, but your Scheduler
// methods already use mutexes, so concurrency is handled.
func (s *GRPCServer) GetTask(ctx context.Context, req *forgepb.GetTaskRequest) (*forgepb.GetTaskResponse, error) {
	log.Printf("Worker %s requesting task", req.WorkerId)

	task := s.scheduler.NextTask()

	if task == nil {
		return &forgepb.GetTaskResponse{
			HasTask: false,
		}, nil
	} else {
		return &forgepb.GetTaskResponse{
			HasTask: true,
			TaskId: task.ID,
			Command: task.Command,
		}, nil
	}
	
}

// ReportResult handles the ReportResult RPC — called by workers when a task finishes.
//
// TODO (Step 4): Implement this method
//
// Steps:
//  1. Call s.scheduler.CompleteTask(req.TaskId, req.Output, int(req.ExitCode))
//  2. Return a response with Ok = true
//
// Note: req.ExitCode is int32 (from protobuf) but CompleteTask takes int.
// You'll need to convert: int(req.ExitCode)
func (s *GRPCServer) ReportResult(ctx context.Context, req *forgepb.ReportResultRequest) (*forgepb.ReportResultResponse, error) {
	log.Printf("Worker %s reporting result for task %s (exit code: %d)", req.WorkerId, req.TaskId, req.ExitCode)

	s.scheduler.CompleteTask(req.TaskId, req.Output, int(req.ExitCode))
	// TODO: Call s.scheduler.CompleteTask() and return ok
	return &forgepb.ReportResultResponse{
		Ok: true,
	}, nil
}
